<?php
function GenrepoVisita($fch, $cte, $obs, $cto, $rta){
$file = fopen($rta, "w");
fwrite($file, 'header("Content-type: application/vnd.ms-word");');
fwrite($file, 'header("Content-Disposition: attachment;Filename=repovisita.doc")');
fwrite($file, '<html>' . PHP_EOL);
fwrite($file, '<head>' . PHP_EOL);
fwrite($file, '<meta content="text/html; charset=UTF-8" http-equiv="content-type">' . PHP_EOL);
fwrite($file, '<style type="text/css">' . PHP_EOL);
fwrite($file, '@import url("https://themes.googleusercontent.com/fonts/css?kit=fpjTOVmNbO4Lz34iLyptLTi9jKYd1gJzj5O2gWsEpXoyck2WCYPEMNySjZN0CHed_kmCvy597kDopqFAXvpeaA");' . PHP_EOL);
fwrite($file, 'ol{margin:0;padding:0}' . PHP_EOL);
fwrite($file, 'table td,table th{padding:0}' . PHP_EOL);
fwrite($file, '.c7{color:#4f81bd;font-weight:700;text-decoration:none;vertical-align:baseline;font-size:26pt;font-family:"Cambria";font-style:italic}' . PHP_EOL);
fwrite($file, '.c1{padding-top:0pt;padding-bottom:10pt;line-height:1.1500000000000001;orphans:2;widows:2;text-align:left;height:11pt}' . PHP_EOL);
fwrite($file, '.c4{padding-top:10pt;padding-bottom:14pt;line-height:1.1500000000000001;orphans:2;widows:2;text-align:center;margin-right:3.1pt}' . PHP_EOL);
fwrite($file, '.c3{padding-top:0pt;padding-bottom:10pt;line-height:1.1500000000000001;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, '.c2{color:#000000;text-decoration:none;vertical-align:baseline;font-style:normal}' . PHP_EOL);
fwrite($file, '.c6{background-color:#ffffff;max-width:441.9pt;padding:70.8pt 85pt 70.8pt 85pt}' . PHP_EOL);
fwrite($file, '.c0{font-size:14pt;font-family:"Calibri";font-weight:400}' . PHP_EOL);
fwrite($file, '.c5{font-weight:400;font-size:8pt;font-family:"Calibri"}' . PHP_EOL);
fwrite($file, '.title{padding-top:0pt;color:#000000;font-size:26pt;padding-bottom:15pt;font-family:"Cambria";line-height:1.0;page-break-after:avoid;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, '.subtitle{padding-top:18pt;color:#666666;font-size:24pt;padding-bottom:4pt;font-family:"Georgia";line-height:1.1500000000000001;page-break-after:avoid;font-style:italic;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, 'li{color:#000000;font-size:11pt;font-family:"Calibri"}' . PHP_EOL);
fwrite($file, 'p{margin:0;color:#000000;font-size:11pt;font-family:"Calibri"}' . PHP_EOL);
fwrite($file, 'h1{padding-top:24pt;color:#000000;font-weight:700;font-size:24pt;padding-bottom:6pt;font-family:"Calibri";line-height:1.1500000000000001;page-break-after:avoid;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, 'h2{padding-top:18pt;color:#000000;font-weight:700;font-size:18pt;padding-bottom:4pt;font-family:"Calibri";line-height:1.1500000000000001;page-break-after:avoid;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, 'h3{padding-top:14pt;color:#000000;font-weight:700;font-size:14pt;padding-bottom:4pt;font-family:"Calibri";line-height:1.1500000000000001;page-break-after:avoid;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, 'h4{padding-top:12pt;color:#000000;font-weight:700;font-size:12pt;padding-bottom:2pt;font-family:"Calibri";line-height:1.1500000000000001;page-break-after:avoid;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, 'h5{padding-top:11pt;color:#000000;font-weight:700;font-size:11pt;padding-bottom:2pt;font-family:"Calibri";line-height:1.1500000000000001;page-break-after:avoid;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, 'h6{padding-top:10pt;color:#000000;font-weight:700;font-size:10pt;padding-bottom:2pt;font-family:"Calibri";line-height:1.1500000000000001;page-break-after:avoid;orphans:2;widows:2;text-align:left}' . PHP_EOL);
fwrite($file, '</style>' . PHP_EOL);
fwrite($file, '</head>' . PHP_EOL);
fwrite($file, '<body class="c6">' . PHP_EOL);
fwrite($file, '<p class="c4" id="h.gjdgxs" style="text-align: center">' . PHP_EOL);
fwrite($file, '<span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #FFFFFF; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 262.75px; height: 89.30px;">' . PHP_EOL);
fwrite($file, '<img alt="" src="imagen logo" style="width: 262.75px; height: 89.30px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title="">' . PHP_EOL);
fwrite($file, '</span><br><br>' . PHP_EOL);
fwrite($file, '<span class="c7">' . PHP_EOL);
fwrite($file, 'Reporte de Visita</span>' . PHP_EOL);
fwrite($file, '</p>' . PHP_EOL);
fwrite($file, '<br><br><br>' . PHP_EOL);
fwrite($file, '<p class="c1">' . PHP_EOL);
fwrite($file, '<span class="c2 c5">' . PHP_EOL);
fwrite($file, '</span>' . PHP_EOL);
fwrite($file, '</p>' . PHP_EOL);
fwrite($file, '<p class="c3">' . PHP_EOL);
fwrite($file, '<span class="c0">' . PHP_EOL);
fwrite($file, 'Fecha: &nbsp; '.$fch.'</span>' . PHP_EOL);
fwrite($file, '</p><br>' . PHP_EOL);
fwrite($file, '<p class="c3">' . PHP_EOL);
fwrite($file, '<span class="c0">' . PHP_EOL);
fwrite($file, 'Cliente: &nbsp;'.utf8_encode($cte).'</span>' . PHP_EOL);
fwrite($file, '</p><hr><br>' . PHP_EOL);
fwrite($file, '<p class="c3">' . PHP_EOL);
fwrite($file, '<span class="c0">' . PHP_EOL);
fwrite($file, 'Observaciones: &nbsp;<br>'.utf8_encode($obs).'</span>' . PHP_EOL);
fwrite($file, '</p><hr><br>' . PHP_EOL);
fwrite($file, '<p class="c3">' . PHP_EOL);
fwrite($file, '<span class="c0">' . PHP_EOL);
fwrite($file, 'Concepto: &nbsp;<br>'.utf8_encode($cto).'</span>' . PHP_EOL);
fwrite($file, '</p><hr><br>' . PHP_EOL);
//-------------------------------------------------- Insertado de cta de cobro
fwrite($file, '<p class="c1"><span class="c6">Cualquier duda, solicitud o sugerencia, no dude en comunicarse con nosotros.</span></p>' . PHP_EOL);
fwrite($file, '<p class="c2 c9"><span class="c11"></span></p>' . PHP_EOL);
fwrite($file, '<p class="c2 c9"><span class="c3"></span></p>' . PHP_EOL);
fwrite($file, '<p class="c2"><span class="c17">Atentamente,</span></p>' . PHP_EOL);
fwrite($file, '<p class="c2 c4"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #FFFFFF; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 368.67px; height: 102.13px;">' . PHP_EOL);
fwrite($file, '<img alt="" src="imagen firma" style="width: 368.67px; height: 102.13px; margin-left: -0.00px; margin-top: -0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title="">' . PHP_EOL);
fwrite($file, '</span></p>' . PHP_EOL);
fwrite($file, '<p class="c2"><span class="c10">Experto en computadores y marketing on line.</span></p>' . PHP_EOL);
fwrite($file, '<p class="c2" id="h.30j0zll"><span class="c11">Cel.: 315 438 39 99</span></p>' . PHP_EOL);
fwrite($file, '<p class="c2"><span class="c11">CompuLG</span></p>' . PHP_EOL);
fwrite($file, '<p class="c2"><span class="c11">Cr. 25 18A 46</span></p>' . PHP_EOL);
fwrite($file, '<p class="c2"><span class="c8">' . PHP_EOL);
fwrite($file, '<a class="c18" href="mailto:servicios@compulg.site">' . PHP_EOL);
fwrite($file, 'servicios@compulg.site</a>' . PHP_EOL);
fwrite($file, '</span></p>' . PHP_EOL);
fwrite($file, '<p class="c2"><span>' . PHP_EOL);
fwrite($file, 'Conoce nuestro Portafolio en: &nbsp;</span><span class="c8">' . PHP_EOL);
fwrite($file, '<a class="c18" href="https://sites.google.com/view/presentacin-compulg/inicio">' . PHP_EOL);
fwrite($file, 'www.compulg.site</a>' . PHP_EOL);
//--------------------------------------------------    
fwrite($file, '</body>' . PHP_EOL);
fwrite($file, '</html>' . PHP_EOL);
}
?>